### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by artelrobotics** [bitmeal/ros-modbus-device-driver#2]
`CMake Error at CMakeLists.txt:35 (add_message_files):
  Unknown CMake command "add_message_files".
`

**Comment by bitmeal** [comment]
Seems like you are trying to configure the build with CMake natively and not using the ROS build system *catkin*.
Besides building with the ROS build system, this package only builds using *[catkin_tools](https://catkin-tools.readthedocs.io/en/latest/index.html)*; see section [building](https://github.com/bitmeal/ros-modbus-device-driver#building) in documentation. See ROS wiki for a [catkin overview](http://wiki.ros.org/catkin/conceptual_overview) and [tutorials](http://wiki.ros.org/ROS/Tutorials) on building ROS packages.
