### ISSUE TITLE
rosdep error

### ISSUE THREAD

**Issue by blueed9696** [bitmeal/ros-modbus-device-driver#4]
`given path 'ros-modbus-device-driver' does not exist`

This error msg happens when I try to `rosdep install -y --from-paths ros-modbus-device-driver`.
How should I solve this?

**Comment by bitmeal** [comment]
I would recommend to familiarize yourself with the required tooling and workflow:
* [*catkin tools*](https://catkin-tools.readthedocs.io/en/latest/)
* [*rosdep*](https://docs.ros.org/en/independent/api/rosdep/html/)
* process of building ROS packages from source (acquired from remote git repos)

for the last one, you can find a concise here https://wiki.nps.edu/display/RC/Setting+up+a+ROS+package+from+Git but be aware that they are not using *catkin tools*, but *catkin_make*.

As for your error:
*rosdep* cannot find the specified path. This tells me you are either in the wrong working directory, or you did not clone the repository. *This is not an error related to the ROS package, but to the usage of the respective tooling.*
